### ISSUE TITLE
No data with splunk-apm version 24

### ISSUE THREAD

**Issue by atrinchillo-mwb** [signalfx/lambda-layer-versions#27]
I just upgraded from version 15 to 24 of splunk apm
No data ingested in the system, I also set debug but no info.

Version 15 works a part of some strage warnings like 
[splunk-extension-wrapper] can't parse bool

Basically I use the splunk apm layer and set configuration to send on signalfx with jaeger 

This is the only log line 
EXTENSION Name: splunk-extension-wrapper State: Ready Events: [INVOKE,SHUTDOWN]

**Comment by kubawach** [comment]
Thanks for the report. Could you give us additional details, such as:
- language used
- configuration options set (besides the token of course ;) )
- CloudWatch logs with "OTEL_LOG_LEVEL", "OTEL_LAMBDA_LOG_LEVEL"  set to "DEBUG" (this is for tracing components)
- CW logs with "VERBOSE" set to "true" (for metrics components)

**Comment by atrinchillo-mwb** [comment]
As mentioned I enabled logging but nothing on it. The system only tell us that the wrapper is loaded 
This is the configuration

    AWS_LAMBDA_EXEC_WRAPPER       = "/opt/otel-instrument"
    OTEL_SERVICE_NAME             = REDACTED
    SPLUNK_REALM                  = "us1"
    SPLUNK_METRICS_ENDPOINT       = "https://ingest.us1.signalfx.com"
    SPLUNK_ACCESS_TOKEN           = REDACTED
    OTEL_RESOURCE_ATTRIBUTES      = "service.name=${REDACTED},deployment.environment=${REDACTED}"
    OTEL_EXPORTER_JAEGER_ENDPOINT = "https://ingest.us1.signalfx.com/v2/trace"
    OTEL_LOG_LEVEL = "DEBUG"
    OTEL_LAMBDA_LOG_LEVEL = "DEBUG"

Sorry it is not clear to me this part:
CW logs with "VERBOSE" set to "true" (for metrics components)

**Comment by kubawach** [comment]
@atrinchillo-mwb please state the layer (ARN) and language you're instrumenting as well
With regards to "VERBOSE" - yet another property, if set to "true" will log debug info about the metrics in the CloudWatch (CW).
With regards to your current configuration - the APM layer uses OTLP exporter by default, so in order to use J/T please add "OTEL_TRACES_EXPORTER: jaeger-thrift-splunk".

**Comment by atrinchillo-mwb** [comment]
OTEL_TRACES_EXPORTER          = "jaeger-thrift-splunk"
Fixed the issue, strangerly with version 15 of apm worked also without this option

Thank you very much

**Comment by kubawach** [comment]
@atrinchillo-mwb yeah, the specification for the serverless evolves and there's been recently switch in default from J/T to OTLP/grpc (which is not yet supported). Hence the issues you experienced. As it's resolved now, I'm closing the issue.
