### ISSUE TITLE
README points to missing/non-public repository

### ISSUE THREAD

**Issue by celkins** [signalfx/lambda-layer-versions#9]
Following the "Main README" link for "SignalFx Metrics Extension" results in HTTP 404:
https://github.com/signalfx/signalfx-extension-wrapper

**Comment by jadbSFx** [comment]
FYI : Until we get that pushed out publically, there is earlier version of documentation at https://github.com/signalfx/lambda-layer-versions/blob/c822fbddca558a20454b8184757a28cccab114a9/lambda-extension/README.md .

**Comment by kubawach** [comment]
Fixed - doc copied from private repository.
